### ISSUE TITLE
[MOBILE] Criar diagrama para obter os detalhes do roteiro

### ISSUE THREAD

**Issue by stings8** [VoyOfficial/voy-app-react-native#44]
Deve-se construir um diagrama arquitetural e de classes para obter os detalhes do roteiro, segue print da tela e link do protótipo:

Link: https://www.figma.com/proto/ub7mXED7TPZasxZ9HSwMW5/Voy!?page-id=0%3A1&node-id=35%3A498&starting-point-node-id=57%3A438

![Image](https://user-images.githubusercontent.com/43052397/221378209-8ecff86b-7339-4c11-8687-92e11be57f0b.png)

**Comment by stings8** [comment]
![Image](https://github.com/VoyOfficial/voy-app-react-native/assets/26841711/0db6dcc2-400a-4453-a853-37fab7e4a9b2)

**Comment by stings8** [comment]
@MarlonBeloMarques criei um diagrama para detalhes de roteiro, se puder validar as propriedades se está faltando alguma, ou nome da classe se faz sentido

**Comment by MarlonBeloMarques** [comment]
@stings8 o que você acha de em vez de ser **Itineraray**, ser **Roadmap**? Já temos um caso de uso que usa esse nome, para retornar os roteiros do usuário.

**Comment by MarlonBeloMarques** [comment]
Sobre as informações, não sei como você está pensando. Exemplo:

- Autor seria um objeto pra ter o nome e foto?
- Tem também a quantidade de lugares e quantas pessoas já salvaram esse roteiro;
- Tem também, se esse roteiro está disponível para a comunidade visualizar ele, ou se ele é privado;
- Tem também, as imagens de cada local.

@stings8 se quiser podemos bater um papo melhor. A proposta é matarmos pelo menos esse diagrama do roteiro e por enquanto não desenvolver ele, para partirmos em conjunto pro MVP.

**Comment by stings8** [comment]
> @stings8 o que você acha de em vez de ser **Itineraray**, ser **Roadmap**? Já temos um caso de uso que usa esse nome, para retornar os roteiros do usuário.

Boa @MarlonBeloMarques vou alterar

**Comment by stings8** [comment]
> Sobre as informações, não sei como você está pensando. Exemplo:
> 
> * Autor seria um objeto pra ter o nome e foto?
> * Tem também a quantidade de lugares e quantas pessoas já salvaram esse roteiro;
> * Tem também, se esse roteiro está disponível para a comunidade visualizar ele, ou se ele é privado;
> * Tem também, as imagens de cada local.
> 
> @stings8 se quiser podemos bater um papo melhor. A proposta é matarmos pelo menos esse diagrama do roteiro e por enquanto não desenvolver ele, para partirmos em conjunto pro MVP.

Massa, pode me chamar qualquer hora pra gente conversar 

- sobre os locais a quantidade pode ser pelo tamanho do array de locais? 
- a imagem eu imagino que venha no objeto de cada local

**Comment by MarlonBeloMarques** [comment]
> > Sobre as informações, não sei como você está pensando. Exemplo:
> > 
> > * Autor seria um objeto pra ter o nome e foto?
> > * Tem também a quantidade de lugares e quantas pessoas já salvaram esse roteiro;
> > * Tem também, se esse roteiro está disponível para a comunidade visualizar ele, ou se ele é privado;
> > * Tem também, as imagens de cada local.
> > 
> > @stings8 se quiser podemos bater um papo melhor. A proposta é matarmos pelo menos esse diagrama do roteiro e por enquanto não desenvolver ele, para partirmos em conjunto pro MVP.
> 
> Massa, pode me chamar qualquer hora pra gente conversar
> 
> * sobre os locais a quantidade pode ser pelo tamanho do array de locais?
> * a imagem eu imagino que venha no objeto de cada local

Temos uma agenda nos dias de terça a noite. Podemos usar ela, tudo bem pra ti?

**Comment by stings8** [comment]
> 

Tudo sim, combinado então

**Comment by stings8** [comment]
> > > Sobre as informações, não sei como você está pensando. Exemplo:
> > > 
> > > * Autor seria um objeto pra ter o nome e foto?
> > > * Tem também a quantidade de lugares e quantas pessoas já salvaram esse roteiro;
> > > * Tem também, se esse roteiro está disponível para a comunidade visualizar ele, ou se ele é privado;
> > > * Tem também, as imagens de cada local.
> > > 
> > > @stings8 se quiser podemos bater um papo melhor. A proposta é matarmos pelo menos esse diagrama do roteiro e por enquanto não desenvolver ele, para partirmos em conjunto pro MVP.
> > 
> > 
> > Massa, pode me chamar qualquer hora pra gente conversar
> > 
> > * sobre os locais a quantidade pode ser pelo tamanho do array de locais?
> > * a imagem eu imagino que venha no objeto de cada local
> 
> Temos uma agenda nos dias de terça a noite. Podemos usar ela, tudo bem pra ti?

Tudo sim, combinado então.

**Comment by MarlonBeloMarques** [comment]
Após alinhado, colocar no padrão inglês e:

- o autor ser um objeto com o nome e foto;
- um atributo para quantidades de locais, ex: quantityPlace;
- um atributo para quantidade de pessoas que salvaram esse roteiro, ex: quantitySaved;
- um atributo para dizer se esse roteiro está disponível para a comunidade ou não;
- a lista de locais, terem somente a imagem de "perfil" e o nome do local;

**Comment by stings8** [comment]
@MarlonBeloMarques da uma olhada se ta ok

![Diagrama em branco-3](https://github.com/VoyOfficial/voy-app-react-native/assets/26841711/1878638a-f7fa-4c6c-8902-1c44dd449113)

**Comment by MarlonBeloMarques** [comment]
> @MarlonBeloMarques da uma olhada se ta ok
> 
> ![Diagrama em branco-3](https://user-images.githubusercontent.com/26841711/264188418-1878638a-f7fa-4c6c-8902-1c44dd449113.png)

Boa Sting, acho que agora tá ok. Pode mover esse cara pra done, que eu vou começar a criar o card de componente de recomendação.
