### ISSUE TITLE
[MOBILE] Criar visualização do Componente: Card de Recomendação

### ISSUE THREAD

**Issue by MarlonBeloMarques** [VoyOfficial/voy-app-react-native#45]
**Criar a visualização do Componente: Card sobre Recomendações.**

Esse componente vai ser utilizado na Home, no Carrossel de Recomendações, por enquanto é somente a visualização, já que estamos definindo ainda contratos etc;

Sugestão sobre o componente:

- Nome: recommendationsListCard;
- Acredito que dá pra reutilizar e criar já alguns utils de cores, fontes etc. Do componente listCard;
- Na minha opinião esse componente não precisa ficar na raiz da camada presentation/components. Por que ele só vai ser usado na lista de recomendações. Poderíamos começar a modularizar a camada de presentation;

Componente:

![Image](https://user-images.githubusercontent.com/43052397/264646953-d9ee0824-20ee-4c47-9fab-bd835c1b946e.png)

Protótipo: https://www.figma.com/file/ub7mXED7TPZasxZ9HSwMW5/Voy!?type=design&node-id=0%3A1&mode=design&t=pW79xKajWGd1xPXu-1

**Comment by MarlonBeloMarques** [comment]
@stings8 qualquer dúvida, só chamar.

**Comment by stings8** [comment]
@MarlonBeloMarques sobre modularizar a cama de presentation ele ficaria em um domain de recommendation, no caso eu precisaria criar a pasta desse domínio e mover os outros arquivos relacionado a eles, isso?

**Comment by MarlonBeloMarques** [comment]
> 
> @MarlonBeloMarques sobre modularizar a cama de presentation ele ficaria em um domain de recommendation, no caso eu precisaria criar a pasta desse domínio e mover os outros arquivos relacionado a eles, isso?

Acredito que sim sting, como é presentation. Talvez uma camada de recomendation dentro de presentation. E aí o componente ficaria dentro de uma pasta components. Foi o que pensei. O que acha?

**Comment by stings8** [comment]
Boa, entendi..
- presentation /
-- recommendation /
--- components /
---- recommendationsListCard ...

tu imagina assim ? ou não faz sentido ter pasta de components dentro?

ou 

- presentation /
-- recommendation /
--- recommendationsListCard ...

@MarlonBeloMarques

**Comment by stings8** [comment]
Outra coisa, como ele está dentro do contexto de recommendation, acha que não fica melhor alterar o recommendationsListCard por listCard ?

**Comment by MarlonBeloMarques** [comment]
> Outra coisa, como ele está dentro do contexto de recommendation, acha que não fica melhor alterar o recommendationsListCard por listCard ?

Faz sentido mano. Boa ideia.

**Comment by MarlonBeloMarques** [comment]
Sobre a pergunta lá encima, acho que a primeira opção é melhor mano.
