### ISSUE TITLE
[MOBILE] Criar Componente para listar as recomendações

### ISSUE THREAD

**Issue by stings8** [VoyOfficial/voy-app-react-native#53]
Criar o Componente: lista de recomendações, utilizando o **recomendation**.

Esse componente é especifico do contexto de Recomendações;

O componente deve ter o seguinte comportamento:
- Título;
- Botão de "Ver todos";
- Uma lista de **recomendation**;

![Image](https://github.com/VoyOfficial/voy-app-react-native/assets/43052397/7f83e4d1-b60b-4c86-a913-061859369275)

**Comment by stings8** [comment]
@MarlonBeloMarques nesse caso seria a página que trás a lista de recomendações ou um componente só com o titulo mesmo e o botão _Ver todos_?

**Comment by MarlonBeloMarques** [comment]
@stings8 é só o componente mesmo de listagem com o título e o botão ver todos.

**Comment by MarlonBeloMarques** [comment]
Aí no caso, na lista. Você vai utilizar o componente de recomendação
