### ISSUE TITLE
[MOBILE] Testar componentes na web

### ISSUE THREAD

**Issue by stings8** [VoyOfficial/voy-app-react-native#65]
Conforme alinhado, iremos lançar o MVP para Web. Para que assim, possamos alcançar o máximo possível de pessoas, aumentando as chances de porta de entrada.

Com isso, devemos testar se todos os componentes criados até então, estão se comportando bem na web.

Como:
- Renderizando corretamente, conforme no Mobile;
- Sem erros ou bugs.

**Comment by MarlonBeloMarques** [comment]
Não vamos mais seguir com a abordagem web por enquanto.
